//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeParaAtmpAlmSistema
    {
        public int Id { get; set; }
        public Nullable<int> IdAut { get; set; }
        public string DescricaoALM { get; set; }
    
        public virtual AUT AUT { get; set; }
    }
}
