//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoTeste_TI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanoTeste_TI()
        {
            this.PlanoTeste_TI_Historico = new HashSet<PlanoTeste_TI_Historico>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> ExecucaoAutomatizada_ATMP { get; set; }
        public string MotivoExecucao_ATMP { get; set; }
        public string OFENSOR_ATMP { get; set; }
        public string Plataforma_ATMP { get; set; }
        public string SUBPROJETO { get; set; }
        public string ENTREGA { get; set; }
        public string PROJETO { get; set; }
        public string PLANO_TESTE { get; set; }
        public decimal TESTE { get; set; }
        public decimal CT { get; set; }
        public string RELEASE { get; set; }
        public string CICLO { get; set; }
        public string FORNECEDOR { get; set; }
        public string SISTEMA { get; set; }
        public string NOME { get; set; }
        public string COMPLEXIDADE { get; set; }
        public string UAT { get; set; }
        public string MASSA_TESTE { get; set; }
        public Nullable<System.DateTime> DT_PLANEJAMENTO { get; set; }
        public Nullable<System.DateTime> DT_EXECUCAO { get; set; }
        public string STATUS_EXEC_CT { get; set; }
        public string MOTIVO_CANCELAMENTO_CT { get; set; }
        public string TESTADOR { get; set; }
        public Nullable<decimal> QT_STEPS { get; set; }
        public string PASTA_LM { get; set; }
        public string CT_AUTOMATIZADO { get; set; }
        public string EXECUCAO_AUTOMATICA { get; set; }
        public string MOTIVO_EXECUCAO_MANUAL { get; set; }
        public string FABRICA_TESTE { get; set; }
        public string ITERATIONS { get; set; }
        public string VARIANTE { get; set; }
        public string PRE_CONDICAO { get; set; }
        public string OBS { get; set; }
        public Nullable<decimal> NRO_CENARIO { get; set; }
        public Nullable<decimal> NRO_CT { get; set; }
        public string EVIDENCIA_VALIDACAO_CLIENTE { get; set; }
        public string EVIDENCIA_VALIDACAO_TECNICA { get; set; }
        public string PLANO_VALIDACAO_CLIENTE { get; set; }
        public string PLANO_VALIDACAO_TECNICA { get; set; }
        public string CT_SUCESSOR { get; set; }
        public string PRE_REQUISITO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string SCRIPT_TOSCA_ATMP { get; set; }
        public string SCRIPT_RFT_ATMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanoTeste_TI_Historico> PlanoTeste_TI_Historico { get; set; }
    }
}
