//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script_CondicaoScript_CT
    {
        public int Id { get; set; }
        public int IdScript_CondicaoScript { get; set; }
        public int IdCT { get; set; }
    
        public virtual CT CT { get; set; }
        public virtual Script_CondicaoScript Script_CondicaoScript { get; set; }
    }
}
